// Generated by CoffeeScript 1.6.2
(function() {
  var addSigners;

  addSigners = function(data) {
    var s, _i, _len, _ref, _results;

    _ref = data.signers;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      _results.push($('ul.signers').append("<li><img src='" + s.picture_url + "' /></li>"));
    }
    return _results;
  };

  $(function() {
    var loading, skip;

    $.getJSON('http://localhost:3000', function(data) {
      addSigners(data);
      $('.signers-count').text(data.count);
      if (data.signed) {
        $('h1.signed').show();
        return $('h1.not-signed').hide();
      }
    });
    skip = 10;
    loading = false;
    return $('a.load-more').click(function() {
      var _this = this;

      if (loading) {
        return;
      }
      loading = true;
      $(this).data('original-text', $(this).text());
      $(this).text('Loading...');
      return $.getJSON("http://localhost:3000/more?skip=" + skip, function(data) {
        addSigners(data);
        skip = skip + data.signers.length;
        loading = false;
        return $(_this).text($(_this).data('original-text'));
      });
    });
  });

}).call(this);
