// Generated by CoffeeScript 1.6.2
(function() {
  var APP_HOST, SPECIAL_SIGNERS, addSigners;

  (function($) {
    return $.getUrlParam = function(key) {
      var result;

      result = new RegExp("" + key + "=([^&]*)", "i").exec(window.location.search);
      return result && unescape(result[1]) || "";
    };
  })(jQuery);

  addSigners = function(data) {
    var $li, s, _i, _len, _ref, _results;

    _ref = data.signers;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      $li = $("<li><img src='" + s.picture_url + "' alt='" + s.name + "' title='" + s.name + "' /></li>");
      _results.push($('ul.signers').append($li));
    }
    return _results;
  };

  APP_HOST = "http://stand-with-todd.herokuapp.com";

  SPECIAL_SIGNERS = [
    {
      name: 'Aneesh Chopra',
      picture_url: 'https://pbs.twimg.com/profile_images/378800000040581867/a0962f4551be12d095b281f8afa81a95.jpeg'
    }, {
      name: "Tim O'Reilly",
      picture_url: 'https://pbs.twimg.com/profile_images/2823681988/f4f6f2bed8ab4d5a48dea4b9ea85d5f1.jpeg'
    }, {
      name: "Eric Reis",
      picture_url: 'https://pbs.twimg.com/profile_images/1769304611/image1327092761.png'
    }, {
      name: "John Tolva",
      picture_url: 'https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash1/273765_835915087_1942680115_n.jpg'
    }, {
      name: 'Cheryl Contee',
      picture_url: 'https://pbs.twimg.com/profile_images/1780647236/Screen_shot_2011-03-31_at_8.33.24_AM.png'
    }, {
      name: 'Janice Fraser',
      picture_url: 'https://pbs.twimg.com/profile_images/1207809084/janice_thumb.jpg'
    }
  ];

  $(function() {
    var initialSkip, loading, skip;

    if ($.getUrlParam('signed')) {
      $('h1.signed').show();
      $('h1.not-signed').hide();
    }
    addSigners({
      signers: SPECIAL_SIGNERS
    });
    initialSkip = 20 - SPECIAL_SIGNERS.length;
    $.getJSON("" + APP_HOST + "?limit=" + initialSkip, function(data) {
      $('.signers-count').text(data.count);
      return addSigners(data);
    });
    skip = initialSkip;
    loading = false;
    return $('a.load-more').click(function() {
      var _this = this;

      if (loading) {
        return;
      }
      loading = true;
      $(this).data('original-text', $(this).text());
      $(this).text('Loading...');
      return $.getJSON("" + APP_HOST + "?skip=" + skip, function(data) {
        addSigners(data);
        skip = skip + data.signers.length;
        loading = false;
        return $(_this).text($(_this).data('original-text'));
      });
    });
  });

}).call(this);
