// Generated by CoffeeScript 1.6.2
(function() {
  var APP_HOST, addSigners;

  (function($) {
    return $.getUrlParam = function(key) {
      var result;

      result = new RegExp("" + key + "=([^&]*)", "i").exec(window.location.search);
      return result && unescape(result[1]) || "";
    };
  })(jQuery);

  addSigners = function(signers) {
    var $li, s, _i, _len, _ref, _results;

    _ref = signers;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      $li = $("<li><img src=\"" + s.image_url + "\" alt=\"" + s.name + "\" title=\"" + s.name + "\" /></li>");
      _results.push($('ul.signers').append($li));
    }
    return _results;
  };

  APP_HOST = "http://petition-backend.herokuapp.com/signers";
  // APP_HOST = "http://localhost:3000/signers";

  $(function() {
    var currentPage, totalPages, loading;

    if ($.getUrlParam('signed')) {
      $('h1.signed').show();
      $('h1.not-signed').hide();
    }

    currentPage = 1;

    $.getJSON("" + APP_HOST + "?page=" + currentPage, function(data) {
      $('.signers-count').text(data.total_signers);

      totalPages = data.total_pages;
      if (currentPage < totalPages){
        $('a.load-more').text('Load More');
      }
      return addSigners(data.signers);
    });
    loading = false;

    return $('a.load-more').click(function() {
      var _this = this;

      currentPage += 1;

      if (loading) {
        return;
      }
      loading = true;
      $(this).text('Loading...');
      return $.getJSON("" + APP_HOST + "?page=" + currentPage, function(data) {
        addSigners(data.signers);
        loading = false;
        if (currentPage < totalPages){
          $('a.load-more').text('Load More');
        } else {
          $('a.load-more').text('');
        }
      });
      });
    });
}).call(this);
